config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "products#index"
  resources :products, only: %i[index show] do
    collection do
      get :web_scraper
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  before_save :generate_slug

  private

  def generate_slug
    self.slug = self.name.parameterize
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :source_url, presence: true, uniqueness: true

  before_save :generate_slug

  private

  def generate_slug
    self.slug = self.title.parameterize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:category_id].present?
      find_category
      products = @category.products.order(created_at: :desc)
      @pagy, @products = pagy(products)
    else
      @pagy, @products = pagy(Product.all)
    end
  end

  def web_scraper
  begin
    url = params[:url]
    @product = WebScraperService.new(url).scrape
  rescue StandardError => e
    flash[:alert] = "An unexpected error occurred: #{e.message}"
  end
  redirect_to products_path
  end

  private

  def find_category
    @category = Category.find_by(id: params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/_header.html.erb
<header class="sticky top-0 z-50 bg-white border-b border-gray-200 dark:bg-gray-800">
  <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
      <a href="/" class="flex items-center p-10">
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Web Scraping</span>
      </a>
     <form action="<%= web_scraper_products_path %>" method="get" class="flex items-center space-x-2">
        <input type="url" name="url" placeholder="Enter URL to scrape"
          class="border rounded-lg px-3 py-2 text-gray-700 dark:text-white dark:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500"
          required>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">
          Scrape
        </button>
      </form>
    </div>
    <div class="overflow-x-auto whitespace-nowrap px-4">
      <div class="flex space-x-4 px-4">
        <% Category.all.each do |category| %>
          <%= link_to category.name, products_path(category_id: category.id), class: "text-gray-700 dark:text-white hover:underline cursor-pointer" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Web Scraping" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="container mx-auto mt-28 px-5">
      <% if flash[:notice] %>
        <div class="flash-message bg-green-500 text-white p-3 rounded-md mb-4">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="flash-message bg-red-500 text-white p-3 rounded-md mb-4">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/index.html.erb
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
  <% @products.each do |product| %>
    <div class="border rounded-lg shadow-md p-4 bg-white">
      <h2 class="text-lg font-semibold"><%= product.title %></h2>
      <p class="text-gray-600"><%= product.description %></p>
      <p class="text-green-500 font-bold"><%= product.price %></p>
    </div>
  <% end %>
</div>
<div class="mt-6 flex justify-center space-x-4">
  <% if @pagy.prev %>
    <%= link_to "Previous", pagy_url_for(@pagy, @pagy.prev), class: "px-4 py-2 bg-gray-200 rounded-md" %>
  <% end %>

  <% (1..@pagy.pages).each do |page| %>
    <% if page == @pagy.page %>
      <span class="px-4 py-2 bg-blue-500 text-white rounded-md"><%= page %></span>
    <% else %>
      <%= link_to page, pagy_url_for(@pagy, page), class: "px-4 py-2 bg-gray-200 rounded-md" %>
    <% end %>
  <% end %>

  <% if @pagy.next %>
    <%= link_to "Next", pagy_url_for(@pagy, @pagy.next), class: "px-4 py-2 bg-gray-200 rounded-md" %>
  <% end %>
</div>